import { Manrope } from "next/font/google";
import "./globals.css";
import FrontendLayout from "@/layout/FrontendLayout/FrontendLayout";

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
  display: "swap",
});

export const metadata = {
  title: "Amplify-Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <FrontendLayout>{children}</FrontendLayout>
      </body>
    </html>
  );
}
